[package]
name = "lewn"
license = "CC0-1.0"
version = "0.9.2"
edition = "2024"
description = "An implementation of Luhn's checksum algorithm using Rust"
repository = "https://github.com/adharmic/lewn"

[dependencies]
clap = {version = "4.5.34", features = ["derive"] }
